discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["ves-${DATACENTRE}-e3", "ves-${DATACENTRE}-e4"]
#discovery.zen.minimum_master_nodes: 3
gateway.expected_nodes: 2
bootstrap.mlockall: true
cluster.name: gca_elasticsearch_${DATACENTRE}
http.port: 9200
http.cors.enabled: true
action.disable_delete_all_indices: true
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: .97
cluster.routing.allocation.disk.watermark.high: .99
